language: php

php:
  - 7.0

branches:
  only:
    - master

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev --no-progress --no-interaction install

script:
  - bin/phpunit
